repos:
  # Clang-Format for C++ code formatting
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
      - id: clang-format
        args: ["--style=Google"]
        files: "\\.(cpp|hpp|cc|h)$"

  # Cpplint for C++ coding conventions
  - repo: https://github.com/cpplint/cpplint
    rev: 2.0.0
    hooks:
      - id: cpplint
        args: ["--extensions=cpp,h,cc,hpp"]
        files: "\\.(cpp|hpp|cc|h)$"

  # Cppcheck from pocc's pre-commit hooks
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: cppcheck
        args: ["--enable=warning", "--suppress=missingInclude", "--language=c++", "--std=c++17"]
        files: "\\.(cpp|hpp|cc|h)$"
        stages: [pre-commit]

  # Generic hooks for trailing whitespaces and other basic checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
