name: cpp_check.yml
on:
  pull_request:

jobs:
  - # Checkout the code
  - name: Checkout code
  - uses: actions/checkout@v3

  - name: Install cppcheck
    run: sudo apt-get install -y cppcheck

  - name: Run static analysis
    run: |
      cppcheck --enable=all --std=c++17 --error-exitcode=1 src/
