name: Pre-Commit Checks

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install cppcheck FIRST
      - name: Install cppcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck

      # Install pre-commit
      - name: Install pre-commit
        run: |
          pip install pre-commit

      # Make sure cppcheck is in PATH by creating symbolic link
      - name: Ensure cppcheck is in PATH
        run: |
          which cppcheck
          sudo ln -sf $(which cppcheck) /usr/local/bin/cppcheck

      # Run pre-commit hooks
      - name: Run pre-commit
        run: |
          pre-commit run --all-files
